#!/bin/python3
import os
import subprocess
import sys

day = None
if len(sys.argv) == 2: day = int(sys.argv[1])

folders = sorted([file for file in os.listdir() if os.path.isdir(file) and file[0].isnumeric()])
def run_solution_in_folder(folder, day):
    name = folder.split("_")[1:]
    for j, word in enumerate(name): name[j] = word.capitalize()
    print(f"Day {day}: {' '.join(name)}")
    os.chdir(folder)
    subprocess.run(["python3", "solution.py"])
    os.chdir("..")
    print("-----")

print("AOC 2024 Solutions")
print("-----")
if day is None:
    for i, folder in enumerate(folders):
        run_solution_in_folder(folder, day=i+1)
else:
    folder = folders[day - 1]
    run_solution_in_folder(folder, day=day)